name: firecrawl

x-common-service: &common-service
  build: apps/api
  networks:
    - backend
  environment:
    - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    - REDIS_RATE_LIMIT_URL=${REDIS_URL:-redis://redis:6379}
    - PLAYWRIGHT_MICROSERVICE_URL=${PLAYWRIGHT_MICROSERVICE_URL:-http://pydoll-service:3003/scrape}
    - PORT=${PORT:-3002}
    - NUM_WORKERS_PER_QUEUE=${NUM_WORKERS_PER_QUEUE}
    - BULL_AUTH_KEY=${BULL_AUTH_KEY}
    - TEST_API_KEY=${TEST_API_KEY}
    - HOST=${HOST:-0.0.0.0}
    - LOGGING_LEVEL=${LOGGING_LEVEL}
    - MAX_RAM=${MAX_RAM:-0.95}
    - MAX_CPU=${MAX_CPU:-0.95}
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  pydoll-service:
    image: trieve/pydoll-service
    build:
      context: .
      dockerfile: ./apps/pydoll-service/Dockerfile
    environment:
      - PORT=3003
      - PROXY_SERVER=${PROXY_SERVER}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - MAX_CONCURRENCY=${MAX_CONCURRENCY}
    networks:
      - backend

  api:
    image: trieve/firecrawl
    <<: *common-service
    depends_on:
      - redis
      - pydoll-service
    ports:
      - "3002:3002"
    command: ["pnpm", "run", "start:production"]

  worker:
    <<: *common-service
    depends_on:
      - redis
      - pydoll-service
      - api
    command: ["pnpm", "run", "workers"]

  redis:
    image: redis:alpine
    networks:
      - backend
    command: redis-server --bind 0.0.0.0

networks:
  backend:
    driver: bridge
