name: Build Docker Images

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-api:
    name: Build API Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/api
          file: ./apps/api/Dockerfile
          push: false
          load: true
          tags: trieve/firecrawl:pr-${{ github.event.number }}
          build-args: |
            PORT=8080

  build-pydoll:
    name: Build Pydoll Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/pydoll-service/
          file: ./apps/pydoll-service/Dockerfile
          push: false
          load: true
          tags: trieve/pydoll-service:pr-${{ github.event.number }}
          build-args: |
            PORT=3003
